"""Generate complex_demo.csv — wide-format healthcare insurance contact center scenario.

Wide format: ConversationID | transcript | MetricCol1 | MetricCol2 | ...
Each metric column = Yes/No/NA ground truth per conversation.
For dynamic (trigger+answer) metrics, NA = trigger did not fire.
"""
import csv
import json

# Wide-format metric columns (these become the rule names shown in the UI)
# For dynamic metrics, the value encodes: Yes=trigger fired+correct, No=trigger fired+wrong, NA=not applicable
METRICS = [
    "Identity Verification",
    "Denied Claim — Appeal Rights",
    "Urgent Medical — Clinical Support",
    "Rx Benefit — Formulary Confirmation",
    "Member Frustration — Acknowledgment",
    "Next Steps Communicated",
    "Proper Call Closure",
]

# ground_truth[conv_id][metric] = "Yes" | "No" | "NA"
# Dynamic metrics: Yes = trigger fired AND answer correct, No = trigger fired AND answer wrong, NA = trigger did not fire
GT = {
    #           Identity   Denied→Appeal  Urgent→Clinical  Rx→Formulary  Frustrated→Ack  NextSteps  Closure
    "conv_001": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"Yes","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_002": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"Yes","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"No"},
    "conv_003": {"Identity Verification":"No","Denied Claim — Appeal Rights":"No","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_004": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"Yes","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"No","Proper Call Closure":"Yes"},
    "conv_005": {"Identity Verification":"No","Denied Claim — Appeal Rights":"Yes","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"No"},
    "conv_006": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"No","Member Frustration — Acknowledgment":"No","Next Steps Communicated":"No","Proper Call Closure":"Yes"},
    "conv_007": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"No","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_008": {"Identity Verification":"No","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"No","Rx Benefit — Formulary Confirmation":"Yes","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_009": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"Yes","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"No","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"No","Proper Call Closure":"Yes"},
    "conv_010": {"Identity Verification":"No","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_011": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"Yes","Rx Benefit — Formulary Confirmation":"Yes","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"No"},
    "conv_012": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"No","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"No","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_013": {"Identity Verification":"No","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"No","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"No","Proper Call Closure":"No"},
    "conv_014": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"No","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_015": {"Identity Verification":"No","Denied Claim — Appeal Rights":"Yes","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"Yes","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"No","Proper Call Closure":"Yes"},
    "conv_016": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"No","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_017": {"Identity Verification":"No","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"No"},
    "conv_018": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"Yes","Rx Benefit — Formulary Confirmation":"No","Member Frustration — Acknowledgment":"Yes","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
    "conv_019": {"Identity Verification":"No","Denied Claim — Appeal Rights":"No","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"No","Proper Call Closure":"Yes"},
    "conv_020": {"Identity Verification":"Yes","Denied Claim — Appeal Rights":"NA","Urgent Medical — Clinical Support":"NA","Rx Benefit — Formulary Confirmation":"NA","Member Frustration — Acknowledgment":"NA","Next Steps Communicated":"Yes","Proper Call Closure":"Yes"},
}

def make_transcript(msgs):
    """msgs: list of (speaker, text). Returns JSON string."""
    result = []
    for i, (speaker, text) in enumerate(msgs):
        result.append({"msg": text, "messageId": i+1, "speaker": speaker, "timestamp": 1800000000 + i*30})
    return json.dumps(result)

CONVERSATIONS = {
"conv_001": make_transcript([
    ("agent",    "Thank you for calling HealthGuard Member Services. This is Priya. How can I help you today?"),
    ("customer", "Hi, I just got a letter saying my MRI claim was denied and I need to understand why."),
    ("agent",    "I'm sorry to hear about that. I can absolutely look into this for you. May I start by getting your member ID?"),
    ("customer", "Yes, it's HG-884721."),
    ("agent",    "Thank you. And can I also confirm your date of birth for security?"),
    ("customer", "April 12, 1978."),
    ("agent",    "Perfect, thank you. I can see your account. The MRI claim from last month was denied due to a missing prior authorization code. I understand this must be really frustrating."),
    ("customer", "This is absolutely frustrating. I got the MRI because my doctor said I needed it urgently. Now I'm being told I have to pay out of pocket?"),
    ("agent",    "I completely understand your frustration and I want to help resolve this. Since the claim has been denied, I do want to make sure you're aware of your appeal rights. You have 180 days from the denial date to submit a formal appeal. I can walk you through that process or send you a written summary."),
    ("customer", "Please send it in writing. What are my chances?"),
    ("agent",    "I can't promise an outcome, but appeals where the physician documents medical necessity are often successful. I'll flag this as expedited. You'll receive acknowledgment within 5 business days and a decision within 30 days. Your case reference is CAS-2841. Is there anything else I can help you with?"),
    ("customer", "No, that's everything. Thank you."),
    ("agent",    "Thank you for calling HealthGuard. Take care."),
]),
"conv_002": make_transcript([
    ("agent",    "HealthGuard Member Services, this is Daniel. How can I assist you?"),
    ("customer", "Hi, I need to know how much my monthly insulin — Lantus — is going to cost. I'm on a fixed income."),
    ("agent",    "Of course. Let me pull up your account. Can I get your member ID please?"),
    ("customer", "Sure, it's HG-331056."),
    ("agent",    "And your date of birth?"),
    ("customer", "November 3, 1952."),
    ("agent",    "Thank you. Looking at your plan — Lantus is on Tier 3 of your formulary. Your cost-sharing for Tier 3 brand medications is a $65 copay for a 30-day supply at a preferred pharmacy, or $45 if you use our mail-order program for a 90-day supply."),
    ("customer", "Oh, the mail order is much cheaper. How do I set that up?"),
    ("agent",    "I can transfer you to our pharmacy benefit team right now and they will get that set up — it usually takes about 10 minutes. Your case reference is CAS-7712."),
    ("customer", "That would be wonderful. Thank you."),
    ("agent",    "Let me transfer you now. Thank you for calling HealthGuard."),
]),
"conv_003": make_transcript([
    ("agent",    "Thank you for calling HealthGuard. My name is Brenda. Who am I speaking with?"),
    ("customer", "This is Marcus Webb."),
    ("agent",    "Hi Mr. Webb, how can I help you today?"),
    ("customer", "I've been trying to get my sleep study claim covered for three months and it keeps getting denied. I'm so fed up with this."),
    ("agent",    "Mr. Webb, I hear you — three months is a long time and I'm sorry you've had to deal with this. Let me look into your claim right now."),
    ("customer", "Thank you. It's just really upsetting. I have sleep apnea and my doctor said this study was medically necessary."),
    ("agent",    "Absolutely. I can see three claim submissions, all denied for the same reason — the study needs to be pre-approved under utilization management requirements. I'm raising an internal escalation so our medical review team looks at this within 5 business days. Your reference number is CAS-9021."),
    ("customer", "Will someone call me back?"),
    ("agent",    "Yes, a case manager will call you within 3 business days. Is there anything else I can help you with today?"),
    ("customer", "No, I just hope this gets sorted. Thank you."),
    ("agent",    "We will do our best, Mr. Webb. Take care."),
]),
"conv_004": make_transcript([
    ("agent",    "HealthGuard Member Services, this is Sandra. How can I help?"),
    ("customer", "Hi, my 4-year-old daughter has had a fever of 103 for the last two days and it's not going down. I'm scared. What do I do? Does my plan cover an ER visit?"),
    ("agent",    "I understand how worrying that must be — let me help you right now. With a fever that high for two days in a child that young, I want to connect you with our 24-hour nurse line so you can speak with a registered nurse immediately. They can advise whether she needs to go to the ER. Can I transfer you right now?"),
    ("customer", "Yes please. But first — will the ER be covered?"),
    ("agent",    "Yes, emergency services are covered. Let me quickly pull up your account to confirm your cost-sharing. Can I get your member ID?"),
    ("customer", "HG-662104."),
    ("agent",    "And date of birth?"),
    ("customer", "Mine is June 22, 1990."),
    ("agent",    "Thank you. Yes, your plan covers emergency room visits with a $250 copay. Now let me get you to the nurse line."),
    ("customer", "Okay, thank you so much."),
    ("agent",    "Of course. Is there anything else before I transfer you?"),
    ("customer", "No, please just get me to the nurse."),
    ("agent",    "Transferring you now. I hope your daughter feels better very soon."),
]),
"conv_005": make_transcript([
    ("agent",    "HealthGuard, this is Tim speaking. What can I help you with today?"),
    ("customer", "Yes, I received a denial for my physical therapy sessions. Sessions 7 through 10 were denied."),
    ("agent",    "I see. Let me look into that. Can you confirm the email address on your account?"),
    ("customer", "It's jkellerman@gmail.com."),
    ("agent",    "I have your account here. Your plan covers physical therapy up to 6 sessions per year without prior authorization. Sessions 7 through 10 require pre-approval, which wasn't obtained."),
    ("customer", "My doctor should have gotten that approval. This isn't my fault."),
    ("agent",    "I understand. You do have the right to appeal this decision. You can submit an appeal within 180 days along with a letter of medical necessity from your doctor. I'll send you the appeal form by email."),
    ("customer", "How long does an appeal take?"),
    ("agent",    "Standard appeals take up to 30 days. Expedited can be 72 hours if medically urgent."),
    ("customer", "Okay, I'll get the form and talk to my doctor."),
    ("agent",    "Sounds good. Good luck with the appeal."),
]),
"conv_006": make_transcript([
    ("agent",    "Thank you for calling HealthGuard. This is Michelle. How can I assist?"),
    ("customer", "Hi, I need help with my drug coverage. I just picked up Humira and it cost me $800 out of pocket. That can't be right."),
    ("agent",    "Let me pull up your account. Can I get your member ID?"),
    ("customer", "HG-441887."),
    ("agent",    "And your date of birth?"),
    ("customer", "March 14, 1965."),
    ("agent",    "Thank you. Specialty medications like Humira can have higher cost-sharing. Your plan does cover Humira but it's a specialty tier medication."),
    ("customer", "I understand it's specialty, but $800? That's outrageous. Nobody told me it would be this expensive. This is completely unacceptable."),
    ("agent",    "I understand. Specialty medications can be expensive. I would suggest looking into our specialty pharmacy program which may reduce your cost-sharing."),
    ("customer", "How much would it reduce it to?"),
    ("agent",    "It varies. I can send you information about the specialty pharmacy program."),
    ("customer", "That's not very helpful. I need a number."),
    ("agent",    "I'm sorry, I don't have the exact amount available right now. Is there anything else I can help you with today?"),
    ("customer", "No. Goodbye."),
    ("agent",    "Thank you for calling. Goodbye."),
]),
"conv_007": make_transcript([
    ("agent",    "HealthGuard Member Services, this is Raj. How can I assist today?"),
    ("customer", "Hi, I'm calling about a claim denial for an ultrasound I had last month. I'm confused about why it was denied."),
    ("agent",    "Of course, let me look into that. Can I start with your member ID?"),
    ("customer", "Yes, it's HG-228934."),
    ("agent",    "And your date of birth, please?"),
    ("customer", "September 5, 1981."),
    ("agent",    "Thank you. I can see the claim for the abdominal ultrasound on March 15th. The denial reason is that the procedure was performed at an out-of-network facility. Your plan requires in-network services for non-emergency procedures."),
    ("customer", "I didn't know that facility was out of network. My doctor referred me there."),
    ("agent",    "That's understandable. When a physician makes a referral, it's still the member's responsibility to verify network status before the appointment."),
    ("customer", "Okay, so what can I do now?"),
    ("agent",    "The best option would be a retroactive exception review. I'll submit that request today. You'll receive a written response within 15 business days. Your case number is CAS-3317. Is there anything else I can help you with?"),
    ("customer", "No, I think that covers it. Thank you."),
    ("agent",    "You're welcome. Have a good day."),
]),
"conv_008": make_transcript([
    ("agent",    "HealthGuard, this is Carlos. What's the reason for your call today?"),
    ("customer", "Hi Carlos, I'm Jane. I've been having chest tightness for a few hours. I also need to ask about my blood pressure medication coverage while I have you on the line."),
    ("agent",    "Hi Jane. Chest tightness for several hours can be serious — if you're experiencing that right now, you should call 911 or go to the nearest emergency room immediately. Please don't delay."),
    ("customer", "I've had this before, it's probably anxiety. I'll be fine. Right now I'm more worried about whether my Lisinopril is going to be covered after my plan changed."),
    ("agent",    "I understand. If symptoms worsen please seek emergency help. Let me check on your Lisinopril coverage. What is your name and I'll pull up your account."),
    ("customer", "Jane Holloway."),
    ("agent",    "Lisinopril is a Tier 1 generic — your copay would be $10 for a 30-day supply or $25 for 90-day at any participating pharmacy."),
    ("customer", "Wait, the pharmacist last week charged me $40. This is so frustrating — I've been on this medication for 10 years and now I'm getting surprise costs."),
    ("agent",    "Jane, I'm sorry to hear that — getting an unexpected charge on a long-term medication is genuinely frustrating and I completely understand why you're upset. Let me investigate that pharmacy charge. It may be that the claim wasn't processed under your new plan ID yet."),
    ("customer", "That would explain it. Can you sort that out?"),
    ("agent",    "I'll submit a claim adjustment request and flag it for our pharmacy team. They'll reach out to the pharmacy directly within 5 business days to correct the charge. Your reference is CAS-5502. Is there anything else I can help you with today?"),
    ("customer", "No, that's what I needed. Thank you."),
    ("agent",    "Thank you for calling. Please do take care of yourself, Jane."),
]),
"conv_009": make_transcript([
    ("agent",    "Thank you for calling HealthGuard Member Services. This is Aisha. How can I help you today?"),
    ("customer", "I have two problems. My Enbrel claim was denied and I've also been told my plan no longer covers Enbrel. I need it for my rheumatoid arthritis."),
    ("agent",    "I understand — dealing with a denial on a critical medication is very stressful. Let me look into both issues. May I have your member ID?"),
    ("customer", "HG-773219."),
    ("agent",    "And your date of birth?"),
    ("customer", "February 28, 1969."),
    ("agent",    "Thank you. I can see the denial — Enbrel was moved to non-formulary on your plan effective January 1st. I know that's very upsetting news when you rely on this medication."),
    ("customer", "It's beyond upsetting. I've been on Enbrel for six years. This is completely unacceptable."),
    ("agent",    "I hear you completely, and I want to make sure you know your options. You have the right to appeal this denial within 180 days. Given six years of use, your rheumatologist can submit a step therapy exception request which has a strong track record for biologic medications."),
    ("customer", "Is Enbrel covered at any tier now?"),
    ("agent",    "It's listed as non-formulary, but the step therapy exception may result in coverage. I need to verify the exact alternative medications required before I can give you a full coverage picture. I'll submit a request for our pharmacy team to send you a detailed formulary comparison by email within 3 business days."),
    ("customer", "Alright. I'll wait for that."),
    ("agent",    "Is there anything else I can help you with today?"),
    ("customer", "No, that's all."),
    ("agent",    "Thank you for your patience, and I hope we can get this resolved for you quickly."),
]),
"conv_010": make_transcript([
    ("agent",    "HealthGuard Member Services. This is Beverly. How may I assist you?"),
    ("customer", "Hi, I'm trying to understand what my plan covers for mental health services. I want to start therapy."),
    ("agent",    "That's a great question. Let me look that up for you. Can I get your member ID?"),
    ("customer", "HG-519273."),
    ("agent",    "Your plan covers outpatient mental health therapy with in-network licensed providers. Your cost-sharing is a $30 copay per session with no visit limit."),
    ("customer", "Are there specific networks I need to use?"),
    ("agent",    "You'll want to use providers in the BlueMind network. I can help you locate one by zip code."),
    ("customer", "That would be great — I'm in zip code 94103."),
    ("agent",    "I have several options near you. I'll email you a list of in-network therapists in that area within 24 hours. Your reference number is CAS-1188."),
    ("customer", "Perfect. Thank you so much."),
    ("agent",    "Of course! Is there anything else I can help you with today?"),
    ("customer", "No, that's all."),
    ("agent",    "Great. Have a wonderful day."),
]),
"conv_011": make_transcript([
    ("agent",    "Thank you for calling HealthGuard. My name is Darnell. How can I assist?"),
    ("customer", "Hi, I need help quickly. My surgeon just told me I need gallbladder surgery within the next few days and I need to make sure it's all covered. I also need to ask about the painkillers I'll be prescribed."),
    ("agent",    "I understand this feels urgent and I'm here to help. Let me pull up your account — can I get your member ID?"),
    ("customer", "HG-992847."),
    ("agent",    "And your date of birth?"),
    ("customer", "July 30, 1976."),
    ("agent",    "Thank you. For surgical pre-authorization with this kind of urgency, I'd like to connect you with a care coordinator who can expedite the prior auth process and coordinate with your surgical team directly. Would that be helpful?"),
    ("customer", "Yes, that would be great."),
    ("agent",    "And for the pain medication question — most post-surgical prescriptions fall under Tier 2. Can you tell me which medication your doctor prescribed?"),
    ("customer", "It's going to be oxycodone."),
    ("agent",    "Oxycodone is a Tier 2 controlled substance. Your copay would be $35 for a 7-day supply. Your plan also requires a quantity limit review for opioids, but for post-surgical use this is typically approved within 24 hours."),
    ("customer", "Okay, good."),
    ("agent",    "I'm going to connect you with a care coordinator now. Your reference for today is CAS-4461."),
    ("customer", "Thank you so much."),
    ("agent",    "Of course. Let me transfer you now."),
]),
"conv_012": make_transcript([
    ("agent",    "HealthGuard Member Services. This is Tanya. What can I do for you today?"),
    ("customer", "I am absolutely livid. My newborn's NICU stay was denied and the bill is $45,000. This is a nightmare."),
    ("agent",    "I understand. Let me pull up your account right away. Member ID please?"),
    ("customer", "HG-114520."),
    ("agent",    "Date of birth?"),
    ("customer", "December 9, 1987."),
    ("agent",    "Thank you. I can see the NICU claim. The denial is because the admitting physician's records show the admission as elective, which triggered a review."),
    ("customer", "Elective? A newborn in the NICU is not elective! This is insane. I can't pay $45,000."),
    ("agent",    "This type of denial is usually correctable. I'll escalate this to our medical review team today as an expedited case and they'll request the attending physician's notes directly. The review team will have a preliminary finding within 72 hours. Your reference number is CAS-8830. Is there anything else?"),
    ("customer", "Are you going to fix this?"),
    ("agent",    "Our review team will work to correct the coding issue. You'll hear back within 72 hours."),
    ("customer", "Fine. I hope so."),
    ("agent",    "Thank you for calling. Goodbye."),
]),
"conv_013": make_transcript([
    ("agent",    "HealthGuard, this is Paul. How can I help?"),
    ("customer", "Hi, I'm going to start Metformin for diabetes. I just want to know if it's covered."),
    ("agent",    "Sure. Can I get your member ID?"),
    ("customer", "HG-667341."),
    ("agent",    "Let me look... yes, Metformin is a covered medication."),
    ("customer", "Great. How much will it cost?"),
    ("agent",    "It should be covered at your plan's generic tier rate."),
    ("customer", "What is that rate exactly?"),
    ("agent",    "It varies — you'd want to check your plan documents or our website for the exact copay."),
    ("customer", "Okay. And can I get it at any pharmacy?"),
    ("agent",    "You can use any participating pharmacy. There may be lower cost options at mail-order pharmacies."),
    ("customer", "Is there a mail-order form?"),
    ("agent",    "Yes, you can find that on our website."),
    ("customer", "Okay, thanks."),
    ("agent",    "Thank you for calling HealthGuard. Goodbye."),
]),
"conv_014": make_transcript([
    ("agent",    "HealthGuard Member Services. This is Gloria. How can I assist you today?"),
    ("customer", "Hi Gloria. I went to the ER last week for chest pain and shortness of breath. The symptoms are still happening on and off. I'm calling to check on the claim but honestly I'm also scared — is there anything HealthGuard can do to help?"),
    ("agent",    "I hear you — ongoing chest pain and shortness of breath continuing after an ER visit is concerning, and I completely understand that you're frightened. Let me get your account up. Can I get your member ID?"),
    ("customer", "HG-283901."),
    ("agent",    "And your date of birth?"),
    ("customer", "May 17, 1958."),
    ("agent",    "Thank you. Your ER claim from last Tuesday is currently in processing — it should complete within 14 business days. Regarding your ongoing symptoms, I'd strongly recommend you follow up with your primary care physician or cardiologist as soon as possible."),
    ("customer", "My doctor's office keeps putting me on hold. It's so frustrating. I've been trying to get an appointment for three days."),
    ("agent",    "I'm sorry you're hitting that wall — that's incredibly frustrating when you're worried about your health. One option is an urgent care clinic, which is covered under your plan with a $75 copay. That might get you seen faster and no referral is needed."),
    ("customer", "Oh, I didn't know urgent care covered this. That's actually helpful."),
    ("agent",    "Yes, and you don't need a referral. Your claim reference for today is CAS-6619. Is there anything else I can help you with?"),
    ("customer", "No, I'll go to urgent care today. Thank you."),
    ("agent",    "Please take care of yourself. Goodbye."),
]),
"conv_015": make_transcript([
    ("agent",    "Thank you for calling HealthGuard. My name is Wayne. How may I help?"),
    ("customer", "Hi Wayne, two things. My dermatologist prescribed Dupixent and I want to know about the coverage. Also, my last dermatology visit claim was denied."),
    ("agent",    "I'll help with both. Which would you like to tackle first?"),
    ("customer", "Let's start with the Dupixent."),
    ("agent",    "Dupixent is a biologic specialty medication. On your current plan, it's a Tier 4 specialty medication. Your cost-sharing for Tier 4 is 20% coinsurance after your deductible, with a maximum out-of-pocket of $500 per month through our specialty pharmacy program."),
    ("customer", "Okay, that's manageable. And the denied claim?"),
    ("agent",    "The dermatology claim was denied because the service code submitted wasn't covered under your plan benefits."),
    ("customer", "That seems like a billing error."),
    ("agent",    "You have 180 days to file a formal appeal. I'd recommend having your dermatologist's billing team resubmit with the correct code, or submit an appeal with the original service notes."),
    ("customer", "Okay, I'll contact their billing office."),
    ("agent",    "Good plan. Is there anything else I can help you with?"),
    ("customer", "No, that's it."),
    ("agent",    "Great, have a good day."),
]),
"conv_016": make_transcript([
    ("agent",    "HealthGuard Member Services, this is Keisha. How can I help today?"),
    ("customer", "I am furious. I had pre-authorization for my knee surgery and it was still denied. How is that possible?"),
    ("agent",    "I can hear how frustrated you are and honestly, having a denial after getting pre-auth is extremely alarming — let me look into this immediately. Can I get your member ID?"),
    ("customer", "HG-956031."),
    ("agent",    "And your date of birth?"),
    ("customer", "August 8, 1972."),
    ("agent",    "Thank you. I can see the pre-authorization and the claim here. There's a discrepancy — the authorization was for the left knee but the claim was submitted for the right knee, which triggered an automatic denial."),
    ("customer", "That's a data entry error. My doctor came to my pre-op appointment. This is a complete mess."),
    ("agent",    "I completely agree this needs to be corrected. I'm escalating this as a priority case — our clinical team will contact your surgeon's office today to correct the laterality code and reprocess the claim. You'll have a resolution within 3 business days. Your reference number is CAS-7753. I'm also adding a notation to pause any collections activity while the correction is in progress."),
    ("customer", "Three business days? This bill is already at collections."),
    ("agent",    "Is there anything else I can help you with?"),
    ("customer", "No. Just fix it."),
    ("agent",    "We will. Thank you for your patience. Goodbye."),
]),
"conv_017": make_transcript([
    ("agent",    "HealthGuard, this is Angela. How may I help?"),
    ("customer", "Hi, I just got my Explanation of Benefits for my annual physical and I'm confused. It says I owe a $20 copay but I thought preventive care was free."),
    ("agent",    "Good question. Let me look at your account. Member ID please?"),
    ("customer", "HG-334782."),
    ("agent",    "Annual preventive physicals are covered at no cost-sharing when the visit is billed entirely as preventive. However, if your doctor addressed other conditions — like reviewing a medication or discussing a chronic condition — that portion can be billed separately and may incur a copay."),
    ("customer", "Oh, the doctor did check my blood pressure and adjusted my medication."),
    ("agent",    "That explains it — the blood pressure management portion was billed as a separate office visit, which carries your $20 copay. I'll send you an itemized breakdown by email within 24 hours."),
    ("customer", "Okay, that makes sense. Thank you."),
    ("agent",    "My pleasure. Goodbye!"),
]),
"conv_018": make_transcript([
    ("agent",    "HealthGuard Member Services. This is Jerome. How can I help you today?"),
    ("customer", "Jerome, I've had severe abdominal pain for two days and I've been vomiting — I can't keep anything down. I also need to talk about my Humira prescription because I'm worried I won't be able to afford it."),
    ("agent",    "I hear you — two days of severe abdominal pain and vomiting sounds serious. Before we do anything else, I want to make sure you're okay. I'd really encourage you to let me connect you with our nurse line right now so they can assess whether you should go to urgent care or the ER. Would you be willing to do that?"),
    ("customer", "I'm trying to avoid the ER because of the cost. That's why I'm calling first."),
    ("agent",    "That's completely understandable. Let me get your account up so we can address the Humira question too. Member ID?"),
    ("customer", "HG-741882."),
    ("agent",    "And your date of birth?"),
    ("customer", "October 21, 1979."),
    ("agent",    "Thank you. Regarding Humira — I can see it's covered under your plan as a specialty medication. I need to check the specialty pharmacy pricing to give you the exact cost-sharing — one moment."),
    ("customer", "This whole situation is so overwhelming. I can't be dealing with financial stress on top of being sick."),
    ("agent",    "I completely understand — being physically unwell and financially stressed at the same time is genuinely overwhelming, and you're right to be concerned about both. Let me focus on getting you the clearest information possible."),
    ("agent",    "Humira is covered but I don't currently have the specialty pharmacy pricing available — I'm going to submit a request for our specialty team to send you an exact quote by email within 24 hours. They can also explore manufacturer assistance programs. Your reference number is CAS-3398. Shall I connect you to the nurse line now?"),
    ("customer", "Yes, please."),
    ("agent",    "Is there anything else before I transfer you?"),
    ("customer", "No, please just connect me."),
    ("agent",    "Right away. Take care."),
]),
"conv_019": make_transcript([
    ("agent",    "HealthGuard, this is Stephanie. How can I help you today?"),
    ("customer", "Hi, I'm calling about a denied claim. I had a sleep study done."),
    ("agent",    "I can help with that. Can I get your name and a phone number to pull up your account?"),
    ("customer", "Thomas Park, and the number is 415-555-9201."),
    ("agent",    "Thank you. I have your account, Mr. Park. I can see the sleep study claim was denied because the facility is out of your plan network and no out-of-network exception was pre-approved."),
    ("customer", "My doctor sent me there. I didn't even know there was a network requirement."),
    ("agent",    "That's a common situation, unfortunately. Out-of-network claims are generally not covered unless there's an emergency or pre-approval."),
    ("customer", "So what do I do? Just pay the full amount?"),
    ("agent",    "You could try reaching out to the facility to negotiate the bill. Sometimes they offer discounts."),
    ("customer", "Okay. I guess I have no other options then."),
    ("agent",    "You're welcome to call us back if you have more questions. Is there anything else I can help you with?"),
    ("customer", "No. Goodbye."),
    ("agent",    "Goodbye, Mr. Park."),
]),
"conv_020": make_transcript([
    ("agent",    "Thank you for calling HealthGuard Member Services. This is Patricia. How may I assist you today?"),
    ("customer", "Hi, I'm considering adding my elderly mother to my plan as a dependent. I need to understand what that process looks like and when I can do it."),
    ("agent",    "Happy to help with that. Let me pull up your account. Member ID please?"),
    ("customer", "HG-102938."),
    ("agent",    "And your date of birth for verification?"),
    ("customer", "January 15, 1988."),
    ("agent",    "Thank you. Adding a dependent outside of your annual open enrollment window is possible through a qualifying life event. Your mother can be added if she qualifies as a tax dependent and meets your plan's dependent eligibility criteria."),
    ("customer", "Open enrollment ended in December. Is there anything I can do now?"),
    ("agent",    "If you have documentation establishing her as a qualifying dependent — such as tax records — I can initiate a special enrollment review. That review takes about 10 business days and I'll submit the request today. Your reference number is CAS-0091."),
    ("customer", "What documents do I need to send?"),
    ("agent",    "You'll need the prior year's tax return showing her as a dependent, and a completed enrollment form which I'll email to you today. Is there anything else I can help you with?"),
    ("customer", "No, that covers it. Thank you, Patricia."),
    ("agent",    "Of course! Have a great day."),
]),
}

header = ["ConversationID", "transcript"] + METRICS
rows = []

for conv_id in sorted(CONVERSATIONS.keys()):
    row = [conv_id, CONVERSATIONS[conv_id]]
    for metric in METRICS:
        row.append(GT[conv_id][metric])
    rows.append(row)

with open("complex_demo.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerow(header)
    writer.writerows(rows)

print(f"Written {len(rows)} rows (wide format) to complex_demo.csv")
print(f"Columns: ConversationID, transcript, + {len(METRICS)} metrics")
